"""Добавлен столбец notified таблицы Finance

Revision ID: 223706a2f5ce
Revises: b5ce36adcf33
Create Date: 2025-10-20 21:46:53.715136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223706a2f5ce'
down_revision: Union[str, Sequence[str], None] = 'b5ce36adcf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance', sa.Column('notified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance', 'notified')
    # ### end Alembic commands ###
