"""Добавлена таблица DoctorSlot

Revision ID: 64475c6766fa
Revises: c4d4ed355c3f
Create Date: 2025-10-18 19:01:16.070216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64475c6766fa'
down_revision: Union[str, Sequence[str], None] = 'c4d4ed355c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appoints', sa.Column('slot_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_records_telegram_id'), table_name='appoints')
    op.create_index(op.f('ix_appoints_telegram_id'), 'appoints', ['telegram_id'], unique=False)
    op.create_foreign_key(None, 'appoints', 'doctor_slots', ['slot_id'], ['id'], ondelete='CASCADE')
    op.drop_column('appoints', 'date_record')
    op.drop_column('appoints', 'doctor')
    op.add_column('doctors', sa.Column('name', sa.String(length=100), nullable=False))
    op.alter_column('doctors', 'speciality',
               existing_type=sa.CHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('doctors', 'time')
    op.drop_column('doctors', 'available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('doctors', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('doctors', 'speciality',
               existing_type=sa.String(length=50),
               type_=sa.CHAR(length=20),
               existing_nullable=False)
    op.drop_column('doctors', 'name')
    op.add_column('appoints', sa.Column('doctor', sa.CHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('appoints', sa.Column('date_record', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appoints', type_='foreignkey')
    op.drop_index(op.f('ix_appoints_telegram_id'), table_name='appoints')
    op.create_index(op.f('ix_records_telegram_id'), 'appoints', ['telegram_id'], unique=False)
    op.drop_column('appoints', 'slot_id')
    op.drop_table('doctor_slots')
    # ### end Alembic commands ###
