"""таблица Appoint, обавлен столбец notified

Revision ID: b5ce36adcf33
Revises: 64475c6766fa
Create Date: 2025-10-19 13:20:17.608778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ce36adcf33'
down_revision: Union[str, Sequence[str], None] = '64475c6766fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Добавляем новый столбец с разрешением NULL
    op.add_column('appoints', sa.Column('notified', sa.Boolean(), nullable=True))

    # 2. Заполняем существующие строки дефолтным значением
    op.execute("UPDATE appoints SET notified = FALSE WHERE notified IS NULL")

    # 3. Меняем колонку на NOT NULL
    op.alter_column(
        'appoints',
        'notified',
        existing_type=sa.Boolean(),
        nullable=False,
        server_default=sa.text('false'),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appoints', 'notified')
    # ### end Alembic commands ###
