"""Таблица Statistics-изменен тип данных contact_phone

Revision ID: c4d4ed355c3f
Revises: 0f3847810719
Create Date: 2025-10-11 19:58:33.174156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4d4ed355c3f'
down_revision: Union[str, Sequence[str], None] = '0f3847810719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE statistics ALTER COLUMN contact_phone TYPE BIGINT USING contact_phone::bigint")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statistics', 'contact_phone',
               existing_type=sa.BigInteger(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
